-- MySQL Script generated by MySQL Workbench
-- Thu Dec 19 15:52:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Beio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Beio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Beio` DEFAULT CHARACTER SET utf8 ;
USE `Beio` ;

-- -----------------------------------------------------
-- Table `Beio`.`FamiliaDispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`FamiliaDispositivo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DescricaoFamilia` TEXT(150) NULL,
  `NomeFamilia` VARCHAR(100) NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`Permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`Permissao` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `Permissao` SMALLINT(2) NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`Empresa` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EmpresaIDFK` INT NOT NULL,
  `Empresa` VARCHAR(100) NULL,
  `CNPJ` VARCHAR(18) NULL,
  `Logo` BLOB NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Empresa_Empresa1_idx` (`EmpresaIDFK` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_Empresa_Empresa1`
    FOREIGN KEY (`EmpresaIDFK`)
    REFERENCES `Beio`.`Empresa` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`Usuario` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PermissaoIDFK` INT NOT NULL,
  `EmpresaIDFK` INT NOT NULL,
  `Nome` VARCHAR(100) NULL,
  `Email` VARCHAR(100) NULL,
  `Senha` VARCHAR(50) NULL,
  `LembrarToken` VARCHAR(150) NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Usuario_Permissao1_idx` (`PermissaoIDFK` ASC) VISIBLE,
  INDEX `fk_Usuario_Empresa1_idx` (`EmpresaIDFK` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Permissao1`
    FOREIGN KEY (`PermissaoIDFK`)
    REFERENCES `Beio`.`Permissao` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Empresa1`
    FOREIGN KEY (`EmpresaIDFK`)
    REFERENCES `Beio`.`Empresa` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`GeoLocalizacaoDispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`GeoLocalizacaoDispositivo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Latitude` VARCHAR(150) NULL,
  `Longitude` VARCHAR(150) NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`Predio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`Predio` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` TEXT(150) NULL,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`Celula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`Celula` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` TEXT(150) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`Area` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` TEXT(150) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`Ambiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`Ambiente` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` TEXT(150) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`Dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`Dispositivo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UsuariosIDFK` INT NOT NULL,
  `FamiliaDispositivoIDFK` INT NOT NULL,
  `GeoLocalizacoesDispositivosIDFK` INT NOT NULL,
  `PredioIDFK` INT NOT NULL,
  `CelulaIDFK` INT NOT NULL,
  `AreaIDFK` INT NOT NULL,
  `AmbienteIDFK` INT NOT NULL,
  `Nome` VARCHAR(100) NULL,
  `DescricaoDispositivo` TEXT(150) NULL,
  `VCC` FLOAT NULL,
  `Gatway` VARCHAR(9) NULL,
  `IP` VARCHAR(9) NULL,
  `Firmware` VARCHAR(9) NULL,
  `RSSI` FLOAT NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  `CEP` VARCHAR(9) NULL,
  `Cidade` VARCHAR(50) NULL,
  `Estado` CHAR(2) NULL,
  `Pais` VARCHAR(50) NULL,
  `Logradouro` VARCHAR(150) NULL,
  `Bairro` VARCHAR(50) NULL,
  `Numero` VARCHAR(20) NULL,
  `Complemeno` TEXT(150) NULL,
  `Bloco` VARCHAR(20) NULL,
  `Andar` VARCHAR(20) NULL,
  `NumeroSala` VARCHAR(20) NULL,
  `PontoInstalacao` TEXT(150) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Dispositivo_FamiliaDispositivo1_idx` (`FamiliaDispositivoIDFK` ASC) VISIBLE,
  INDEX `fk_Dispositivos_Usuarios1_idx` (`UsuariosIDFK` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Dispositivos_GeoLocalizacoesDispositivos1_idx` (`GeoLocalizacoesDispositivosIDFK` ASC) VISIBLE,
  INDEX `fk_Dispositivo_Predio1_idx` (`PredioIDFK` ASC) VISIBLE,
  INDEX `fk_Dispositivo_Celula1_idx` (`CelulaIDFK` ASC) VISIBLE,
  INDEX `fk_Dispositivo_Area1_idx` (`AreaIDFK` ASC) VISIBLE,
  INDEX `fk_Dispositivo_Ambiente1_idx` (`AmbienteIDFK` ASC) VISIBLE,
  CONSTRAINT `fk_Dispositivo_FamiliaDispositivo1`
    FOREIGN KEY (`FamiliaDispositivoIDFK`)
    REFERENCES `Beio`.`FamiliaDispositivo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dispositivos_Usuarios1`
    FOREIGN KEY (`UsuariosIDFK`)
    REFERENCES `Beio`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dispositivos_GeoLocalizacoesDispositivos1`
    FOREIGN KEY (`GeoLocalizacoesDispositivosIDFK`)
    REFERENCES `Beio`.`GeoLocalizacaoDispositivo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dispositivo_Predio1`
    FOREIGN KEY (`PredioIDFK`)
    REFERENCES `Beio`.`Predio` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dispositivo_Celula1`
    FOREIGN KEY (`CelulaIDFK`)
    REFERENCES `Beio`.`Celula` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dispositivo_Area1`
    FOREIGN KEY (`AreaIDFK`)
    REFERENCES `Beio`.`Area` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dispositivo_Ambiente1`
    FOREIGN KEY (`AmbienteIDFK`)
    REFERENCES `Beio`.`Ambiente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`Sensore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`Sensore` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `DescricaoSensor` TEXT(150) NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`Protocolo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`Protocolo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Protocolo` VARCHAR(10) NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`Api`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`Api` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ProtocolosIDFK` INT NOT NULL,
  `Metodo` VARCHAR(10) NULL,
  `Resposta` TINYINT NULL,
  `Endereco` VARCHAR(150) NULL,
  `Arquitetura` VARCHAR(10) NULL,
  `Modulo` TINYINT NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Api_Protocolos1_idx` (`ProtocolosIDFK` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_Api_Protocolos1`
    FOREIGN KEY (`ProtocolosIDFK`)
    REFERENCES `Beio`.`Protocolo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`RegistroApi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`RegistroApi` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DispositivosIDFK` INT NOT NULL,
  `ApiIDFK` INT NOT NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_RegistrosApi_Api1_idx` (`ApiIDFK` ASC) VISIBLE,
  INDEX `fk_RegistrosApi_Dispositivos1_idx` (`DispositivosIDFK` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_RegistrosApi_Api1`
    FOREIGN KEY (`ApiIDFK`)
    REFERENCES `Beio`.`Api` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegistrosApi_Dispositivos1`
    FOREIGN KEY (`DispositivosIDFK`)
    REFERENCES `Beio`.`Dispositivo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`DadoColetadoSensore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`DadoColetadoSensore` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DispositivoIDFK` INT NOT NULL,
  `SensoresIDFK` INT NOT NULL,
  `RegistrosApiIDFK` INT NOT NULL,
  `DadoColetadoSensor` VARCHAR(50) NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_DadosColetadosSensores_Sensores1_idx` (`SensoresIDFK` ASC) VISIBLE,
  INDEX `fk_DadosColetadosSensores_Dispositivo1_idx` (`DispositivoIDFK` ASC) VISIBLE,
  INDEX `fk_DadosColetadosSensores_RegistrosApi1_idx` (`RegistrosApiIDFK` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_DadosColetadosSensores_Sensores1`
    FOREIGN KEY (`SensoresIDFK`)
    REFERENCES `Beio`.`Sensore` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DadosColetadosSensores_Dispositivo1`
    FOREIGN KEY (`DispositivoIDFK`)
    REFERENCES `Beio`.`Dispositivo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DadosColetadosSensores_RegistrosApi1`
    FOREIGN KEY (`RegistrosApiIDFK`)
    REFERENCES `Beio`.`RegistroApi` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`Atributo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`Atributo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `DescricaoAtributo` TEXT(150) NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`DadoColetadoAtributo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`DadoColetadoAtributo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DispositivosIDFK` INT NOT NULL,
  `AtributosIDFK` INT NOT NULL,
  `RegistrosApiIDFK` INT NOT NULL,
  `DadoColetadoAtributo` VARCHAR(50) NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_DadosColetadosAtributos_Atributos1_idx` (`AtributosIDFK` ASC) VISIBLE,
  INDEX `fk_DadosColetadosAtributos_Dispositivos1_idx` (`DispositivosIDFK` ASC) VISIBLE,
  INDEX `fk_DadosColetadosAtributos_RegistrosApi1_idx` (`RegistrosApiIDFK` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_DadosColetadosAtributos_Atributos1`
    FOREIGN KEY (`AtributosIDFK`)
    REFERENCES `Beio`.`Atributo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DadosColetadosAtributos_Dispositivos1`
    FOREIGN KEY (`DispositivosIDFK`)
    REFERENCES `Beio`.`Dispositivo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DadosColetadosAtributos_RegistrosApi1`
    FOREIGN KEY (`RegistrosApiIDFK`)
    REFERENCES `Beio`.`RegistroApi` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`Evento` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Parametro` VARCHAR(50) NULL,
  `Valor` VARCHAR(50) NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`EnderecoEmpresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`EnderecoEmpresa` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EmpresaIDFK` INT NOT NULL,
  `Descricao` TEXT(150) NULL,
  `CEP` VARCHAR(9) NULL,
  `Cidade` VARCHAR(50) NULL,
  `Estado` CHAR(2) NULL,
  `Pais` VARCHAR(50) NULL,
  `Logradouro` VARCHAR(150) NULL,
  `Bairro` VARCHAR(50) NULL,
  `Numero` VARCHAR(20) NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_EnderecosDispositivos_copy1_Empresa1_idx` (`EmpresaIDFK` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_EnderecosDispositivos_copy1_Empresa1`
    FOREIGN KEY (`EmpresaIDFK`)
    REFERENCES `Beio`.`Empresa` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`Grafico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`Grafico` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`Dashbord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`Dashbord` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UsuariosIDFK` INT NOT NULL,
  `DispositivosIDFK` INT NOT NULL,
  `GraficosIDFK` INT NOT NULL,
  `Descricao` TEXT(150) NULL,
  `Ordem` INT NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Dashbord_Dispositivos1_idx` (`DispositivosIDFK` ASC) VISIBLE,
  INDEX `fk_Dashbords_Usuarios1_idx` (`UsuariosIDFK` ASC) VISIBLE,
  INDEX `fk_Dashbords_Graficos1_idx` (`GraficosIDFK` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_Dashbord_Dispositivos1`
    FOREIGN KEY (`DispositivosIDFK`)
    REFERENCES `Beio`.`Dispositivo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dashbords_Usuarios1`
    FOREIGN KEY (`UsuariosIDFK`)
    REFERENCES `Beio`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dashbords_Graficos1`
    FOREIGN KEY (`GraficosIDFK`)
    REFERENCES `Beio`.`Grafico` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`DashbordSensore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`DashbordSensore` (
  `DashbordsIDFK` INT NOT NULL,
  `SensoresIDFK` INT NOT NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  PRIMARY KEY (`DashbordsIDFK`, `SensoresIDFK`),
  INDEX `fk_Dashbords_has_Sensores_Sensores1_idx` (`SensoresIDFK` ASC) VISIBLE,
  INDEX `fk_Dashbords_has_Sensores_Dashbords1_idx` (`DashbordsIDFK` ASC) VISIBLE,
  CONSTRAINT `fk_Dashbords_has_Sensores_Dashbords1`
    FOREIGN KEY (`DashbordsIDFK`)
    REFERENCES `Beio`.`Dashbord` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dashbords_has_Sensores_Sensores1`
    FOREIGN KEY (`SensoresIDFK`)
    REFERENCES `Beio`.`Sensore` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`FiltroGrafico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`FiltroGrafico` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TipoGrafico` VARCHAR(50) NULL,
  `Valor` VARCHAR(50) NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`FiltroGraficoDashbord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`FiltroGraficoDashbord` (
  `FiltrosGraficosIDFK` INT NOT NULL,
  `DashbordsIDFK` INT NOT NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  PRIMARY KEY (`FiltrosGraficosIDFK`, `DashbordsIDFK`),
  INDEX `fk_FiltrosGraficos_has_Dashbords_Dashbords1_idx` (`DashbordsIDFK` ASC) VISIBLE,
  INDEX `fk_FiltrosGraficos_has_Dashbords_FiltrosGraficos1_idx` (`FiltrosGraficosIDFK` ASC) VISIBLE,
  CONSTRAINT `fk_FiltrosGraficos_has_Dashbords_FiltrosGraficos1`
    FOREIGN KEY (`FiltrosGraficosIDFK`)
    REFERENCES `Beio`.`FiltroGrafico` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FiltrosGraficos_has_Dashbords_Dashbords1`
    FOREIGN KEY (`DashbordsIDFK`)
    REFERENCES `Beio`.`Dashbord` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`UsuarioLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`UsuarioLog` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UsuariosIDFK` INT NOT NULL,
  `Nome` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `Sessao` TINYINT NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_UsuariosLogs_Usuarios1_idx` (`UsuariosIDFK` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_UsuariosLogs_Usuarios1`
    FOREIGN KEY (`UsuariosIDFK`)
    REFERENCES `Beio`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beio`.`RecuperacaoSenha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beio`.`RecuperacaoSenha` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UsuariosIDFK` INT NOT NULL,
  `Email` VARCHAR(100) NULL,
  `Token` VARCHAR(150) NULL,
  `DataCadastro` TIMESTAMP(4) NULL,
  `DataAtualizacao` TIMESTAMP(4) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_RecuperacoesSenhas_Usuarios1_idx` (`UsuariosIDFK` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_RecuperacoesSenhas_Usuarios1`
    FOREIGN KEY (`UsuariosIDFK`)
    REFERENCES `Beio`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
